plugins {
    id 'common'
    id 'publish-mods'
    id 'java-library'
}

dependencies {
    compileOnly(project(':common'))
}

tasks.named('compileJava', JavaCompile) {
    source(project(':common').sourceSets.main.allSource)
}

processResources {
    from project(":common").sourceSets.main.resources
    from file("../common/src/generated")
}