plugins {
    id 'me.modmuss50.mod-publish-plugin'
}

publishMods {
    displayName = file.map { it.asFile.name }
    type = STABLE

    var changelogFile = rootProject.file('CHANGELOG.md')
    if (changelogFile.exists()) changelog = changelogFile.text
    else changelog = 'NO VALID CHANGELOG FILE FOUND!'

    modrinth {
        accessToken = MODRINTH_API_KEY
        projectId = modrinth_id

        requires('resource-library')
        requires('resource-config-api')
    }

    curseforge {
        accessToken = CURSEFORGE_API_KEY
        projectId = curseforge_id

        clientRequired = true
        serverRequired = true

        javaVersions.add(JavaVersion.VERSION_21)

        requires('resource-library')
        requires('resource-config-api')
    }
}