org.gradle.jvmargs=-Xmx8192M
org.gradle.daemon=false

version=3.1.3
group=net.morthen
java_version=25

modrinth_id=hwfBSwLz
curseforge_id=917988

# Common
minecraft_version=26.2

mod_id=resource_cracker
mod_name=Resource Cracker
mod_author=Morthen
mod_license=MIT
mod_description=Gather Resources with ease

neoform=26.2-2
neoforge=26.2.0.54-beta
fabric_api=0.156.0+26.2
fabric_loader=0.19.3
forge=65.1.0

resourcelibrary=4.0.3
resourceconfigapi=4.1.1

# Additional stuff
sources_url=https://github.com/Morthen-Mods/Resource-Cracker
issues_url=https://github.com/Morthen-Mods/Resource-Cracker/issues