org.gradle.jvmargs=-Xmx8192M
org.gradle.daemon=false

# Project
version=2.5.0
group=net.xstopho.resource_cracker
java_version=21
modrinth_id=hwfBSwLz
curseforge_id=917988

# Common
mod_name=Resource Cracker
mod_author=xStopho
mod_id=resource_cracker
mod_license=MIT
mod_description=Gather Resources with ease