org.gradle.jvmargs=-Xmx8192M
org.gradle.deamon=false

# Project
version=3.0.2
group=net.morthen.resource_cracker
java_version=25
modrinth_id=hwfBSwLz
curseforge_id=917988

# Common
mod_name=Resource Cracker
mod_author=Morthen
mod_id=resource_cracker
mod_license=MIT
mod_description=Gather Resources with ease

# Plugins
fabric_loom=1.17-SNAPSHOT
forge_gradle=7.0.30
moddev_gradle=2.0.141
mod_publish=2.0.1
mixin_version=0.8.7
mixin_extras=0.3.5

# Loader stuff
minecraft_version=26.1.2
neoform=26.1.2-1
fabric_api=0.153.0
fabric_loader=0.19.3
neoforge=26.1.2.76
forge=64.0.10

# Dependencies
mod_menu=18.0.0-beta.1
resource_config_api=4.1.1
resource_library=3.1.2