plugins {
    id 'ml-common'
    id 'net.neoforged.moddev'
}

dependencies {
    implementation "net.xstopho.resourceconfigapi:resourceconfigapi-neoforge:${minecraft_version}-${resource_config_api}"
    implementation "net.xstopho.resourcelibrary:resourcelibrary-neoforge:${minecraft_version}-${resource_library}"

    implementation project(":1.21.1:common")
}

neoForge {
    version = neoforge_21_1

    def at = file('../common/src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) accessTransformers = [at]

    parchment {
        minecraftVersion = minecraft_version
        mappingsVersion = parchment_21_1
    }

    runs {
        data {
            data()
            ideName = "Common Datagen (1.21.1)"
            gameDirectory = file('../common/runs/data')
            programArguments = ['--mod', project.mod_id, '--all', '--output', file('../common/src/generated/').getAbsolutePath(), '--existing', file('../common/src/main/resources/').getAbsolutePath()]
        }
    }
    mods {
        "${mod_id}" { sourceSet sourceSets.main }
    }
}

compileJava {
    source(project(':1.21.1:common').sourceSets.main.allSource)
}

processResources {
    from project(":1.21.1:common").sourceSets.main.resources
}