name: New Issue/Bug other than mod support requests
description: Only report one issue, if you have multiple issues please create multiple bug reports. This makes it easier to track.
labels: ["bug"]
assignees: ["Stein-N"]
body:
  - type: dropdown
    id: mod-loader
    attributes:
      label: Mod loader
      options:
        - Please Select
        - Fabric
        - NeoForge
        - Forge
        - Quilt
      default: 0
    validations:
      required: true
  - type: input
    id: mod-version
    attributes:
      label: Mod version
      placeholder: eg. 1.0.0
    validations:
      required: true
  - type: input
    id: mc-version
    attributes:
      label: Minecraft version
      placeholder: eg. 1.20.1
    validations:
      required: true
  - type: textarea
    attributes:
      label: Issue description
      description: Also provide steps to reproduce the bug if you can.
      placeholder: A description of the bug/suggestion.
    validations:
      required: true
  - type: checkboxes
    id: reproducible
    attributes:
      label: If Bug
      options:
        - label: "I have confirmed this bug is reproducible on a minimal setup, not a modpack with many other mods."
  - type: input
    attributes:
      label: "Provide the latest.log file"
      description: "Please use a paste site such as [gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc."