name: New Feature/Enhancement
description: Only request one Feature at a Time. This makes it easier to track.
labels: ["feature request"]
assignees: ["Stein-N"]
body:
  - type: textarea
    attributes:
      label: Feature
      description: Describe what the Feature/Enhancement should be.
      placeholder: A description of the feature/enhancement
    validations:
      required: true
  - type: textarea
    attributes:
      label: Dependency Mods
      description: Provide the Curseforge or Modrinth link for the Mods this Feature would require or depends on.
      placeholder: https://modrinth.com/mod/trinkets