plugins {
    id 'loader'
    id 'net.fabricmc.fabric-loom'
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"

    implementation "net.fabricmc:fabric-loader:${fabric_loader}"
    api "net.fabricmc.fabric-api:fabric-api:${fabric_api}+${minecraft_version}"

    implementation "net.xstopho.resourceconfigapi:resourceconfigapi-fabric:${minecraft_version}-${resource_config_api}"
    implementation "net.xstopho.resourcelibrary:resourcelibrary-fabric:${minecraft_version}-${resource_library}"

    implementation "com.terraformersmc:modmenu:${mod_menu}"
}

loom {
    mixin {
        defaultRefmapName.set("${mod_id}.refmap.json")
    }

    def aw = file("src/main/resources/${mod_id}.accesswidener")
    if (aw.exists()) accessWidenerPath.set(aw)

    runs {
        client {
            client()
            setConfigName("Fabric Client")
            ideConfigGenerated(true)
            programArgs('--username', 'Dev')
            runDir("runs/client")
        }
        server {
            server()
            setConfigName("Fabric Server")
            ideConfigGenerated(true)
            runDir("runs/server")
        }
    }
}

publishMods {
    file = jar.archiveFile
    modLoaders.addAll("fabric", "quilt")

    modrinth { requires("fabric-api") }
    curseforge { requires("fabric-api") }
}