modLoader = "javafml"
loaderVersion = "${neoforge_loader_version_range}"
license = "${mod_license}"

[[mods]]
    modId = "${mod_id}"
    version = "${mod_version}"
    displayName = "${mod_name}"
    authors = "${mod_author}"
    description = '''${mod_description}'''
    logoFile = "icon.png"

[[mixins]]
    config = "${mod_id}.mixins.json"
[[mixins]]
    config = "${mod_id}.neoforge.mixins.json"

[[dependencies.${mod_id}]]
    modId = "neoforge"
    mandatory = true
    versionRange = "${neoforge_loader_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "minecraft"
    mandatory = true
    versionRange = "${minecraft_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "simpleconfigapi"
    mandatory = true
    versionRange = "[0.2.5, )"
    ordering = "NONE"
    side = "BOTH"

