plugins {
    id 'ml-loader'
    id 'net.neoforged.moddev'
}

dependencies {
    implementation "net.xstopho.resourceconfigapi:resourceconfigapi-neoforge:${minecraft_version}-${resource_config_api}"
    implementation "net.xstopho.resourcelibrary:resourcelibrary-neoforge:${minecraft_version}-${resource_library}"
}

neoForge {
    version = neoforge_21_6

    def at = file('../common/src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) accessTransformers = [at]

    parchment {
        minecraftVersion = "1.21.5"
        mappingsVersion = parchment_21_6
    }

    runs {
        configureEach {
            systemProperty('neoforge.enableGameTestNamespaces', mod_id)
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})"
            gameDirectory = file("../common/runs/${it.name.toLowerCase()}")
        }
        client {
            client()
        }
        server {
            server()
            programArguments.add('nogui')
        }
    }
    mods {
        "${mod_id}" { sourceSet sourceSets.main }
    }
}
publishMods {
    file = jar.archiveFile
    modLoaders.addAll("neoforge")

    modrinth {
        minecraftVersions.addAll("1.21.6")
    }
    curseforge {
        minecraftVersions.addAll("1.21.6")
    }
}
