# Common
minecraft_version=1.21.5
minecraft_version_range=[1.21.5, 1.21.6]

neoform_version=1.21.5-20250325.162830
parchment_version=2025.01.19

# Fabric
fabric_api_version=0.119.5
fabric_loader_version=0.16.10

# NeoForge
neoforge_version=21.5.0-beta

# Forge
forge_version=54.0.21
forge_version_range=[54, 55)

# Dependencies
resource_config_api=1.21.5-3.6.0
resource_library=1.21.5-2.5.0

# Runtime Mods
mod_menu=14.0.0-rc.1